<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.8.22" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.1" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LogisticsPlatform.Domain\LogisticsPlatform.Domain.csproj" />
  </ItemGroup>

</Project>
