export enum Permission {
    Load_View = 'Load_View',
    Load_Create = 'Load_Create',
    Load_Update = 'Load_Update',
    Load_Operational_Update = 'Load_Operational_Update',
    Load_ChangeStatus = 'Load_ChangeStatus',
    Load_Archive = 'Load_Archive',
    Load_Dispatch = 'Load_Dispatch',
    Load_Tender = 'Load_Tender',
    Load_AssignDelayResponsibility = 'Load_AssignDelayResponsibility',
    Load_Tracking_View = 'Load_Tracking_View',
    Load_Tracking_Update = 'Load_Tracking_Update',
    Financial_Invoice_UpdateStatus = 'Financial_Invoice_UpdateStatus',
    Financial_Invoice_RecordPayment = 'Financial_Invoice_RecordPayment',
    Financial_Settlement_UpdateStatus = 'Financial_Settlement_UpdateStatus',
    Financial_Settlement_RecordPayment = 'Financial_Settlement_RecordPayment',

    CarrierOffer_View = 'CarrierOffer_View',
    CarrierOffer_View_All = 'CarrierOffer_View_All',
    CarrierOffer_Create = 'CarrierOffer_Create',
    CarrierOffer_Accept = 'CarrierOffer_Accept',
    CarrierOffer_Reject = 'CarrierOffer_Reject',

    LoadException_View = 'LoadException_View',
    LoadException_Create = 'LoadException_Create',
    LoadException_Update = 'LoadException_Update',

    LoadStopService_View = 'LoadStopService_View',
    LoadStopService_Create = 'LoadStopService_Create',
    LoadStopService_Delete = 'LoadStopService_Delete',
    Load_CompletedCorrection = 'Load_CompletedCorrection',
    OrderCost_View = 'OrderCost_View',
    OrderCost_Update = 'OrderCost_Update',
    LoadCost_View = 'LoadCost_View',
    LoadCost_Update = 'LoadCost_Update',
    Financial_View = 'Financial_View',

    LoadNote_View = 'LoadNote_View',
    LoadNote_Create_Internal = 'LoadNote_Create_Internal',
    LoadNote_Create_Public = 'LoadNote_Create_Public',

    LoadDocument_View = 'LoadDocument_View',
    LoadDocument_Upload = 'LoadDocument_Upload',
    LoadDocument_Delete = 'LoadDocument_Delete',

    User_View_All = 'User_View_All',
    User_View_Self = 'User_View_Self',
    User_Update = 'User_Update',
    User_Delete = 'User_Delete',
    User_AssignRole = 'User_AssignRole',
    User_Disable = 'User_Disable',
    Customer_View = 'Customer_View',
    Customer_Create = 'Customer_Create',
    Customer_Update = 'Customer_Update',
    Customer_Delete = 'Customer_Delete',

}
