export const PermissionLabels: Record<string, string> = {
    Load_View: 'View Loads',
    Load_Create: 'Create Loads',
    Load_Update: 'Edit Loads',
    Load_Operational_Update: 'Edit Load Operations',
    Load_ChangeStatus: 'Change Load Status',
    Load_Dispatch: 'Dispatch Loads',
    Load_Tracking_View: 'View Load Tracking',
    Load_Tracking_Update: 'Update Load Tracking',
    LoadCost_View: 'View Load Costs',
    LoadCost_Update: 'Edit Load Costs',
    OrderCost_View: 'View Order Costs',
    OrderCost_Update: 'Edit Order Costs',
    Financial_View: 'View Financials',
    Financial_Invoice_UpdateStatus: 'Update Invoice Status',
    Financial_Invoice_RecordPayment: 'Record Invoice Payment',
    Financial_Settlement_UpdateStatus: 'Update Settlement Status',
    Financial_Settlement_RecordPayment: 'Record Settlement Payment',
    User_Update: 'Edit Users',
    User_Disable: 'Disable Users'
};
