import { environment } from '../../../environments/environment';

export const API_ENDPOINTS = {
    auth: `${environment.apiBaseUrl}/auth`,
    users: `${environment.apiBaseUrl}/users`,
    customers: `${environment.apiBaseUrl}/customers`,
    carriers: `${environment.apiBaseUrl}/carriers`,
    customerAddresses: `${environment.apiBaseUrl}/customer-addresses`,
    customerContacts: `${environment.apiBaseUrl}/CustomerContacts`,
    customerNotes: `${environment.apiBaseUrl}/CustomerNotes`,

    orders: `${environment.apiBaseUrl}/orders`,
    orderItems: `${environment.apiBaseUrl}/orders`,
    orderRoutes: `${environment.apiBaseUrl}/orders`,
    orderEquipmentRequirements: `${environment.apiBaseUrl}/orders`,
    orderCosts: `${environment.apiBaseUrl}/orders`,
    orderNotes: `${environment.apiBaseUrl}/orders`,
    orderDocuments: `${environment.apiBaseUrl}/orders`,
    orderExternalIds: `${environment.apiBaseUrl}/orders`,
    loadsFromOrder: `${environment.apiBaseUrl}/loads/from-order`,
    loads: `${environment.apiBaseUrl}/loads`,
    carrierOffers: `${environment.apiBaseUrl}/carrier-offers`,
    loadStops: `${environment.apiBaseUrl}/loads`,
    loadStopExecution: `${environment.apiBaseUrl}/load-stops`,
    loadItems: `${environment.apiBaseUrl}/loads`,
    loadEquipment: `${environment.apiBaseUrl}/loads`,
    loadCosts: `${environment.apiBaseUrl}/loads`,
    loadNotes: `${environment.apiBaseUrl}/loads`,
    loadDocuments: `${environment.apiBaseUrl}/loads`,
    financialInvoices: `${environment.apiBaseUrl}/financials/invoices`,
    financialSettlements: `${environment.apiBaseUrl}/financials/settlements`,
    delayResponsibility: `${environment.apiBaseUrl}/delay-responsibility`,
    tablePreferences: `${environment.apiBaseUrl}/ui/table-preferences`,
    notifications: `${environment.apiBaseUrl}/notifications`,
    globalSearch: `${environment.apiBaseUrl}/search`,
    publicCarrierTenders: `${environment.apiBaseUrl}/public/carrier-tenders`,

};
